# Welcome to Jekyll!
#

# Site settings
title: PURPLE SHARK EMBROIDERY
description: |
 Our Passion is bring your Logo to Life!<br/>
 Priding ourselves in fast quality turnaround & Friendly Custom Service!
owner: Purple Shark Embroidery # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: info@purplesharkembroidery.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.purplesharkembroidery.com" # the base hostname & protocol for your site
googapi: AIzaSyDvaO0KRLtWwqhZjZLH_nAjsVt1NuX_xMc
social:
  #twitter: https://twitter.com/<username>
  instagram: https://instagram.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/purplesharkembroidery/
  email: info@purplesharkembroidery.com
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
